//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musica
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MusicaEntities : DbContext
    {
        public MusicaEntities()
            : base("name=MusicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALBUM> ALBUM { get; set; }
        public virtual DbSet<ARTISTA> ARTISTA { get; set; }
        public virtual DbSet<CANCION> CANCION { get; set; }
        public virtual DbSet<GENERO> GENERO { get; set; }
    }
}
